name: IssueOps

on: 
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  actions: write


jobs:
  process-command:
    if: contains(github.event.comment.body, '/issueops')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Run add_repo script
      if: contains(github.event.comment.body, '/issueops add_repo')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INVITATIONS_CSV_PATH: ${{ secrets.INVITATIONS_CSV_PATH }}
      run: python scripts/add_repo.py

    - name: Run add script
      if: contains(github.event.comment.body, '/issueops add')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COLLABORATORS_CSV_PATH: ${{ secrets.COLLABORATORS_CSV_PATH || 'default/path/to/collaborators.csv' }}
        
      run: python scripts/add.py

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Debug Comment Body
      run: echo "${{ github.event.comment.body }}"
