name: IssueOps

on: 
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  actions: write

jobs:
  process-command:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Run add_repo script
      if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/issueops add_repo')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INVITATIONS_CSV_PATH: ${{ github.workspace }}/invitations.csv
      run: |
        if [ -f "$INVITATIONS_CSV_PATH" ]; then
          python scripts/add_repo.py
        else
          echo "Error: invitations.csv not found at $INVITATIONS_CSV_PATH"
          exit 1
        fi

    - name: Run add script
      if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/issueops add')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COLLABORATORS_CSV_PATH: ${{ github.workspace }}/collaborators.csv
      run: |
        if [ -f "$COLLABORATORS_CSV_PATH" ]; then
          python scripts/add.py
        else
          echo "Error: collaborators.csv not found at $COLLABORATORS_CSV_PATH"
          exit 1
        fi

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Debug Comment Body
      if: github.event_name == 'issue_comment'
      run: echo "${{ github.event.comment.body }}"