name: Simple Test

on:
  issue_comment:
    types: [created]
  push:
    branches: [ main, Dummy ] # Allow the build when there is a commit to Main or Tests branches.
  pull_request:
    branches: [ main, Dummy ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm ci
    - run: npm run build
    - run: npm test
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

  process-command:
    if: contains(github.event.comment.body, '/issueops')
    runs-on: ubuntu-latest
    steps:
      - name: Set up debug logging
        run: echo "::set-env name=ACTIONS_STEP_DEBUG::true"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run add_repo script
        if: contains(github.event.comment.body, '/issueops add_repo')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INVITATIONS_CSV_PATH: 'scripts/invitations.csv'  # Set the CSV path as environment variable
        run: python scripts/add_repo.py

      - name: Run add script
        if: contains(github.event.comment.body, '/issueops add')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COLLABORATOR_CSV_PATH: 'scripts/collaborator.csv'  # Set the CSV path as environment variable
        run: python scripts/add.py

  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print comment info
      run: |
        echo "Issue comment event received"
        echo "Comment body: ${{ github.event.comment.body }}"
