name: Simple Test

on:
  issue_comment:
    types: [created]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print comment info
      run: |
        echo "Issue comment event received"
        echo "Comment body: ${{ github.event.comment.body }}"
