name: IssueOps

on:
  issue_comment:
    types: [created]

jobs:
  test-trigger:
    if: contains(github.event.comment.body, '/issueops')
    runs-on: ubuntu-latest
    steps:
    - name: Echo test
      run: echo "Workflow triggered by comment:${{github.event.comment.body}}"

  process-command:
    if: contains(github.event.comment.body, '/issueops')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Run add_repo script
      if: contains(github.event.comment.body, '/issueops add_repo')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python scripts/add_repo.py

    - name: Run add script
      if: contains(github.event.comment.body, '/issueops add')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python scripts/add.py